server:
  port: 8888
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/danielcelestino/configserver.git
          #username: username
          #password: password
          #default-label: main
          search-paths:
          - 'greeting-service*'